name: WordPress Tests

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: [ "8.1", "8.2", "8.3", "8.4" ]

    name: PHP ${{ matrix.php-versions }} Test on ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup MySQL 8.0 with mysql_native_password
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: "8.0"
          my-cnf: |
            bind_address=127.0.0.1
            default-authentication-plugin=mysql_native_password
          root-password: root

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
          extensions: mysql, mysqli
          tools: composer, wp-cli, phpunit-polyfills:1.1

      - name: Composer install
        run: composer install --optimize-autoloader --prefer-dist

      - name: Install SVN
        run: sudo apt-get update && sudo apt-get install -y subversion

      - name: Install WP Tests
        run: bash bin/install-wp-tests.sh wordpress_test root root 127.0.0.1 latest

      - name: PHPUnit tests
        run: |
          echo "define('WP_TESTS_PHPUNIT_POLYFILLS_PATH', '$HOME/.composer/vendor/yoast/phpunit-polyfills');" >> /tmp/wordpress-tests-lib/wp-tests-config.php
          phpunit --config=phpunit.xml
